import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import "./../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="relative overflow-x-hidden">
      <SidebarProvider>
        <AppSidebar />
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <SidebarTrigger />
            <div 
                className="absolute top-0 left-0 -translate-x-1/2 -translate-y-1/2 w-[60rem] h-[60rem] bg-purple-100/50 rounded-full blur-3xl -z-100" 
                aria-hidden="true" 
            />
            <div 
                className="absolute bottom-0 right-0 translate-x-1/2 translate-y-1/2 w-[60rem] h-[60rem] bg-indigo-100/50 rounded-full blur-3xl -z-100" 
                aria-hidden="true" 
            />
          {children}
        </body>
      </SidebarProvider>
    </div>
  );
}
